### ISSUE TITLE
Не запускается проект через Docker Compose

### ISSUE THREAD

**Issue by maksim4k1** [akarmanov2022/project-place#2]
Когда пытаюсь запустить проект через docker-compose PostgreSQL запускается нормально, а сам проект падает со следующей ошибкой:
![{13BF336C-040D-4337-AED7-8CA872766FB9}](https://github.com/user-attachments/assets/952420f1-4d28-485f-91a1-4233cf244e86)
![{3F9EBCA5-4E75-4D88-9C4A-378897BF1F72}](https://github.com/user-attachments/assets/c6243d63-6e22-4f59-88bd-51bd15e6e97b)

**Comment by akarmanov2022** [comment]
Исправлено. Просьба пересобрать контейнер. Также дополнил инструкцию по запуску в README.md.
